grid_length: 128
encoder: # transformer encoder config
    dim: 256
    num_layers: 6
    num_head: 1
    dim_feedforward: 128
training:
    dataset_ratio: [0.8, 0.1, 0.1] # Ratio for train, val and test set.
    learning_rate: 0.0001 # 1e-04
    weight_decay: 0.0001 # 1e-04
    batch_size: 256
    padding_value: -0.5
eval:
    batch_size: 64
